###########################################
#     Manifests for api server
###########################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageserver
  labels:
    app: imageserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageserver
  template:
    metadata:
      labels:
        app: imageserver
    spec:
      containers:
      - name: server
        image: raghunandanbs/imageserver:v2
        ports:
        - containerPort: 8080

